# Generated by Django 6.1 on 2026-08-17 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=255)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emergency_available', models.BooleanField(default=False)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_identity_verified', models.BooleanField(default=False)),
                ('is_police_verified', models.BooleanField(default=False)),
                ('is_certificate_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
