# Generated by Django 6.1 on 2026-08-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='working_days',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='working_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
